module.exports.ERROR_CODE_WRONG_DATA = 400;
module.exports.ERROR_CODE_WRONG_EMAIL_OR_PASSWORD = 401;
module.exports.ERROR_CODE_WRONG_ID = 404;
module.exports.ERROR_CODE_EMAIL_ALREADY_EXIST = 409;
module.exports.ERROR_CODE_UNKNOWN_SERVER_ERROR = 500;
